### ISSUE TITLE
Only one enchantment possible per item in 0.17 alpha 6

### ISSUE THREAD

**Issue by Katalijst** [xenondevs/Nova#418]
### Agreements

- [X] I am using an official build of Nova.
- [X] I am running the latest version of Nova.
- [X] I am using a [server software supported by Nova](https://docs.xen.cx/nova/admin/compatibility/#compatible-server-software)
- [X] I am running the latest version of my server software.
- [X] I have checked for similar issues.

### Check for plugin incompatibilites

There are no other plugins running on my server.

### Plugin Version, Server Software, Server Version

Nova-0.17-alpha.6 ; paper-1.21.1-13

### Nova Addons and Versions

My WIP addon

### Expected behavior

I shoud be able to apply multiple enchant to my items

### Observed/Actual behavior

I am not able to apply multiple enchant to my items

### Steps to reproduce

```kt
    val ENCHANTABLE_SHOVEL = item("enchantable_shovel") {
        behaviors(Tool, Damageable, Enchantable, Extinguishing, Flattening)
        maxStackSize(1)
    }
```
```yaml
# Enchantable Options
enchantment_value: 10
supported_enchantments:
  - minecraft:fortune
  - minecraft:silk_touch
  - minecraft:efficiency
  - minecraft:unbreaking
  - minecraft:mending
  - minecraft:vanishing_curse
  ```
Then try to add enchant to this item using /enchant or with anvil and book

### Server log

[2024-08-16-24.log](https://github.com/user-attachments/files/16641763/2024-08-16-24.log)
